### ISSUE TITLE
Implement new card design

### ISSUE THREAD

**Issue by kdjohnson** [joshherkness/AR-Top#113]
ellipsis button, open button

**Comment by kdjohnson** [comment]
@joshherkness 
<img width="1430" alt="screen shot 2018-01-31 at 7 58 17 pm" src="https://user-images.githubusercontent.com/11354738/35655689-1e6bc1a8-06c1-11e8-8658-d63e0fbed211.png">
<img width="1402" alt="screen shot 2018-01-31 at 7 58 40 pm" src="https://user-images.githubusercontent.com/11354738/35655698-2e2d1452-06c1-11e8-83ed-706eec4042a4.png">

**Comment by joshherkness** [comment]
Looks good to me

**Comment by joshherkness** [comment]
Maybe have the delete be red, like the sign out link?

**Comment by joshherkness** [comment]
Are you ready to merge this in, or do we want to wait until it is synced with the REST endpoint?

**Comment by joshherkness** [comment]
- #118 - on how to open a map in the editor
- #121 - on how to open delete map modal
- #122 - on how to open edit map modal

**Comment by kdjohnson** [comment]
Merged.
