### ISSUE TITLE
Create grid

### ISSUE THREAD

**Issue by joshherkness** [joshherkness/AR-Top#14]
# Create grid

Create a script that can be used to render a grid of size `n * m`. Account for possibility of `n` and `m` having a zero and negative value. In these cases, simply do not render a grid. Get this ready to demo in AR. __See if using a prefab would be the best option__

If possible, experiment with placing letters and numbers on rows and columns.

Ideally, we will be placing `GridEntities` onto this to create our map.

**Comment by joshherkness** [comment]
Would this be a prefab?

**Comment by goeteeks** [comment]
It would probably use a prefab object and a script that duplicates the object n x m times.
