### ISSUE TITLE
Session manager component

### ISSUE THREAD

**Issue by joshherkness** [joshherkness/AR-Top#152]
Construct the session manager component as seen in https://drive.google.com/open?id=1p7XhJjiUTd-SJqLQ4sSHkvgLXOCRob9E.

See #153 for related issue on vuex

**Comment by kdjohnson** [comment]
<img width="1440" alt="screen shot 2018-02-11 at 4 17 41 pm" src="https://user-images.githubusercontent.com/11354738/36078610-1d9f065c-0f47-11e8-8fa3-d31eb9693999.png">

**Comment by kdjohnson** [comment]
@joshherkness Anything else you want included in this issue?

**Comment by joshherkness** [comment]
Maybe the open session link also?

**Comment by kdjohnson** [comment]
OK. I'll add it in.

**Comment by kdjohnson** [comment]
So, we'll have a dropdown item that says open session. From there do we want to take them to the library and let them select open session from there. Or opening a modal with a list of possible maps to create a session for? Is this in scope with this issue?

**Comment by joshherkness** [comment]
Changed to this https://www.draw.io/?state=%7B%22ids%22:%5B%221DKKUPds03UolSIG_3ddwIa7CZv98NeGg%22%5D,%22action%22:%22open%22,%22userId%22:%22110704134673537721752%22%7D#G1DKKUPds03UolSIG_3ddwIa7CZv98NeGg
