### ISSUE TITLE
Style join session view

### ISSUE THREAD

**Issue by joshherkness** [joshherkness/AR-Top#159]
Style the join session view on mobile, following [this](https://drive.google.com/open?id=1dwQAH0H-sqpH1kZQInyyDl6GV_vnX3XW) mockup design.

- Note that the keyboard on mobile will take up screen space. Look into some sort of keyboard avoiding view, or resize the view accordingly.

**Comment by joshherkness** [comment]
@goeteeks is this done?

**Comment by nlferman** [comment]
The panel aspect is done. It still needs to be placed in its own scene.

**Comment by nlferman** [comment]
Oh hey, this is done now.
