### ISSUE TITLE
Registration is broken

### ISSUE THREAD

**Issue by joshherkness** [joshherkness/AR-Top#166]
# Steps to reproduce

1. Attempt to register an account

Something might be broken with the API service method used to register on the client side.

**Comment by kdjohnson** [comment]
As of  f51dfe2 this works for me.

**Comment by joshherkness** [comment]
Hm... I'm getting 422 error code when I do this.

**Comment by joshherkness** [comment]
Flask log says that `mercer@exandria.net` is a duplicate email key. I'm not even sending that as the email...

**Comment by joshherkness** [comment]
I had to drop the User and GameMap tables in my database, then everything worked. It looks like something I had in my database in the past was messing with my ability to register a new account. That is odd.
