### ISSUE TITLE
Deploy Unity App to Mobile

### ISSUE THREAD

**Issue by nlferman** [joshherkness/AR-Top#169]
Getting a start on Deploying the Unity App to Android Phones.
Note that iOS phones require a Mac with Xcode v7.3 or greater to deploy to them.

**Comment by joshherkness** [comment]
Deploying to iOD requires the following:

1. Enable Vuforia AR support in `Player > XR Settings`
2. Change Graphics API from Metal to Open GLES2 in `Player > iOS Settings`

**Comment by joshherkness** [comment]
Can you create a wiki page with necessary steps to perform on the unity side for this? Since this task is not really code provable.

**Comment by joshherkness** [comment]
Can this be closed out?
