### ISSUE TITLE
Edit map does not work in library list view

### ISSUE THREAD

**Issue by joshherkness** [joshherkness/AR-Top#200]
For some reason, editing properties of a map does not update in UI immediately upon submit in the library list view.

### Steps

1. Create a map (or use existing map)
2. Attempt to change the map name
3. Map name does not change in the UI
4. Refresh page
5. Map name should not be changed

**Comment by joshherkness** [comment]
There seems to be something causing this in the server. Whenever the update_map function is called, it will return the original map in the response, but still save the map.

`update_map(new_map) -> *save new map* -> return old_map`, sorta.

**Comment by kdjohnson** [comment]
This should be fixed here e756e1b.
