### ISSUE TITLE
Fix issue where "full" grid outlines appear on update

### ISSUE THREAD

**Issue by nlferman** [joshherkness/AR-Top#254]
Presently if the viewer holds their camera over the image target when they receive an update, the full grid outlines will be displayed despite their settings. If they move the camera off of the target and bock on, the proper grid outlines will then be displayed. We want this to be fixed so that the proper outlines appear all of the time.

**Comment by joshherkness** [comment]
Is this complete?

**Comment by nlferman** [comment]
This will be a non-issue with the new Voxel models. I will have to remove some code in a couple of places, though.

**Comment by nlferman** [comment]
I am going to close this issue and make a new issue for general clean-up of stuff Unity no longer needs.
