### ISSUE TITLE
Unity add back key functionality

### ISSUE THREAD

**Issue by nlferman** [joshherkness/AR-Top#255]
Add a function so if a viewer presses the back key on their phone it does something (brings up the leave menu if in the main scene, or asks to confirm quitting the app if in Login scene).

Also will add a quit application button to the Login scene.

**Comment by joshherkness** [comment]
I believe that it's been decided that we will not implement a "quit application" button within the application.

**Comment by joshherkness** [comment]
And you are correct. When a viewer presses the "back" button, they will immediately be disconnected from their current session, and returned to the login scene.

**Comment by joshherkness** [comment]
The back button, along with all other viewer buttons (focus, settings) should not be visible on the login scene.
