### ISSUE TITLE
JSON Format

### ISSUE THREAD

**Issue by joshherkness** [joshherkness/AR-Top#34]

**Comment by joshherkness** [comment]
```
{
  width: 16 ,
  height: 16,
  depth: 5,
  models: [
    {
      type: "voxel",
      position: {
        x: 0,
        y: 3,
        z: 10,
     },
     color: {
        r: 0.3,
        g: 0.1,
        b: 0.4,
        a: 1.0
      }
    }
  ]
}
```

**Comment by goeteeks** [comment]
Unity's Vector4 recognizes the values as x, y, z, w, so we can't use r, g, b, a as the variable for each color value if we want to use colors as a Vector4 type.

**Comment by joshherkness** [comment]
[this](https://docs.unity3d.com/ScriptReference/Color.html) says that "Colors can be implicitly converted to and from Vector4"


"

**Comment by goeteeks** [comment]
So apparently I can just change the Vector4 to a Color. and Colors have attributes of r, g, b, a. So we can use those instead of x, y, z, w.

Also, you can use either 0-255, or 0-1.0 for the values. I did some playing around with it.

**Comment by joshherkness** [comment]
Good

**Comment by joshherkness** [comment]
You should also probably use a Vector3 to represent the (width, height, depth).  This way, you can say something like size.x , size.y, size.z which give the actual dimentions to the size.

**Comment by joshherkness** [comment]
I'll be specifying the color in terms of 0.0 to 1.0

**Comment by goeteeks** [comment]
I was thinking we could add a Vector3 for the rotation of piece objects. We can also add a vector3 for the scale, too. Is this for the map as a whole or individual objects?

**Comment by joshherkness** [comment]
Ideally, we would want a Vector3 for anything that is using 3 dimensions, in order to reduce repetitive code.

**Comment by goeteeks** [comment]
Agreed.

**Comment by AnthonyHewins** [comment]
alright i want to put this here so yall can pick it apart for the fields I have selected

```
class ColorField(BaseField):
    r = IntegerField(default=0, choices=range(0,256))
    g = IntegerField(default=0, choices=range(0,256))
    b = IntegerField(default=0, choices=range(0,256))
    a = DecimalField(default=0, min_value=0, max_value=1)
        
class Map(Model):
    width = IntegerField(default=16, choices=range(1,50000))
    height = IntegerField(default=5, choices=range(1,50000))
    depth = IntegerField(default=16, choices=range(1,50000))
    base_color = ColorField()
    model = ListField() #default is [], meaning empty map
```

map inherits from model which has metadata attached to it, so i excluded that.
I'd like to know if i should place restrictions on the size of certain elements too

**Comment by goeteeks** [comment]
So I made the discovery that 0-255 range numbers won't work in Unity (for color). If we're going to do individual RGBA values for colors, it has to be from 0 - 1 as a float. Josh also wants to look into a way to use #RRGGBBAA format for the color instead.

**Comment by joshherkness** [comment]
Ya, saving the hex value would be easier for me, and take less data. I believe unity will be able to handle it.

**Comment by joshherkness** [comment]
Maybe limit width height depth to 1024

**Comment by joshherkness** [comment]
And rename the model field to models

**Comment by joshherkness** [comment]
And add some sort of field to represent public vs private?

**Comment by AnthonyHewins** [comment]
added what yall suggested.

dont know if its worthwhile to add a voxel as a model too:
```
class Voxel(BaseField):
    color = BinaryField()
    x = IntField(required=True, choices=range(1,max_size + 1))
    y = IntField(required=True, choices=range(1,max_size + 1))
    z = IntField(required=True, choices=range(1,max_size + 1))
```
