### ISSUE TITLE
Unity: Grid

### ISSUE THREAD

**Issue by joshherkness** [joshherkness/AR-Top#39]
Would [this](https://gist.github.com/mdomrach/a66602ee85ce45f8860c36b2ad31ea14) work for the Unity grid?

**Comment by goeteeks** [comment]
This draws a flat nxn grid. We already have a way of doing a flat nxm grid. Was this what you were trying to do or were you trying to find something that draws wireframes around a cube?

**Comment by joshherkness** [comment]
I'm trying to find a more modular way of adding a grid using lines.  This would allow things like changing the grid color in the future. I believe this could also be expanded in the future to draw nxm if we need it.
