### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by joshherkness** [joshherkness/AR-Top#42]
### Create a home page for our web application.

- Should have navigation bar at the top of the page.
- Since the user must be logged in to view this page, make it a protected route. (i.e. a user must be have a valid auth_token)
- Pull the user email and display it in the top right of the navigation bar.

**Comment by joshherkness** [comment]
Should this be converted to 'map list' page as discussed?

**Comment by kdjohnson** [comment]
I think it makes since to have a homepage that just has the map list as a component. That way we still have the option to be modular with it later on if we decide to change.

**Comment by kdjohnson** [comment]
Also, I'll take care of issues #48 and #49 on this branch.

**Comment by joshherkness** [comment]
Alright, that sounds fine.  So maybe /home/maps and /home/editor, and the home route is protected such that a user must be authenticated, otherwise they are returned to /auth route?
