### ISSUE TITLE
API: read map endpoint

### ISSUE THREAD

**Issue by joshherkness** [joshherkness/AR-Top#61]
### API: read map endpoint  - GET /api/map/:id
- Request must contain a valid auth token
  - Otherwise return  401 Unauthorized
- Respond with map containing the id

### Notes
- Make sure the owner of the map containing this id is the same as that providing the auth token. You should only be able to access a map if it is yours.

**Comment by jjrobertson14** [comment]
Endpoint is done, testing of it is not

**Comment by jjrobertson14** [comment]
Created a new issue and branch for testing, closing issue
