### ISSUE TITLE
API: update map endpoint

### ISSUE THREAD

**Issue by joshherkness** [joshherkness/AR-Top#63]
### API: update map endpoint -  PUT/api/map/:id
- Request must contain a valid auth token
  - Otherwise return  401 Unauthorized
- Respond with updated map
- Override last_updated date upon update

**Comment by AnthonyHewins** [comment]
our plan for this is to send the entirety of the map right? not just the parts that changed?

**Comment by joshherkness** [comment]
Correct

**Comment by AnthonyHewins** [comment]
hey so mongoengine supports upserting, is that potentially better than having two separate routes for update and insert?

**Comment by joshherkness** [comment]
I suppose. Keep in mind that we might not send the whole map payload, maybe just something like the id of the map and the name (for updating the map name)

**Comment by joshherkness** [comment]
- Update map endpoint needs some work to function more like the `create map` endpoint as created in #118.
- Should return the newly updated map
- Should seamlessly handle any type of update.
  - i.e. If I pass it the following post, it should update only the provided map properties (name, color). All others should remain the same.

```
POST /api/map/<id>
{
  name: 'New name'
  color: '#ffffff'
}
```

**Comment by joshherkness** [comment]
@AnthonyHewins

**Comment by AnthonyHewins** [comment]
this isn't hard to do except for the 'models' part, which im assuming you will just send the entire thing if it changes at all?

**Comment by joshherkness** [comment]
Correct
