### ISSUE TITLE
API: read list of maps by user id

### ISSUE THREAD

**Issue by joshherkness** [joshherkness/AR-Top#64]
### API: read list of maps by user id - GET /api/maps/:user_id
- Request must contain a valid auth token
  - Otherwise return  401 Unauthorized
- Respond with list of maps, or empty list

### Notes
- Only the author of a map should be able to access their map through this endpoint. Ensure that the user_id param matches that stored in the provided auth_token

**Comment by joshherkness** [comment]
How much longer until this is complete?

**Comment by kdjohnson** [comment]
Done.
