### ISSUE TITLE
Registration endpoint

### ISSUE THREAD

**Issue by joshherkness** [joshherkness/AR-Top#7]
# Registration endpoint

This endpoint will be used to register an account with our API. Upon successful registration, the system should send the user a email confirmation. 

* **URL**
  * `/register`

* **Method**
  * `POST`

* **URL Params**
  * _None_

* **Data Params**
  * `{ email=[alphanumeric], password=[alphanumeric] }`

* **Successful response**
  * **Code**: `200`
     **Content**: _None_

* **Error response**
  * **Code**: `422`
     **Content**: `{ error: "Email already in use"}`
  
  OR
 
  * **Code**: `422`
     **Content**: `{ error: "Email is not valid" }`

  OR

  * **Code**: `422`
     **Content**: `{ error: "Password does not satisfy minimum length" }`

* **Sample call**

```javascript
axios.post('/register', {
  email: "mercer@exandria.net",
  password: "p@ssw0rd"
})
.then((res) => {
  console.log(response)
})
.catch((err) => {
  console.log(error)
})
```

* **Notes**
  * By default a user should be created with a `verified` flag of `False`, indicating that they have not yet verified their email

**Comment by joshherkness** [comment]
Take a look at this https://github.com/mattupstate/flask-security/issues/421

**Comment by kdjohnson** [comment]
@AnthonyHewins I didn't see that you moved this issue to In progess. My bad. Not sure if you want to use it but I did have some code for this issue [here](https://github.com/joshherkness/AR-Top/tree/9-registration-endpoint/server)
