### ISSUE TITLE
Unity: create custom AR image target

### ISSUE THREAD

**Issue by joshherkness** [joshherkness/AR-Top#70]
Create/find a suitable image that can be uploaded to Vuforia as our image target.

- Should have a score of at least 4 stars

**Comment by joshherkness** [comment]
Maybe these would be nice.

https://ih1.redbubble.net/image.182315960.0324/flat,800x800,070,f.u1.jpg

http://www.beanleafpress.com/wp-content/uploads/2011/01/dice.jpg

https://78.media.tumblr.com/20aafad1213f20e75990830a31269317/tumblr_oyym3h1QmZ1wzv1vxo1_500.jpg

**Comment by nlferman** [comment]
Those are all 5 stars with a good amount of features. I think the lone D20 might be the best, but they all could work pretty well.
