### ISSUE TITLE
Map card component

### ISSUE THREAD

**Issue by joshherkness** [joshherkness/AR-Top#79]
Create map card component as seen in the following mockup.  https://drive.google.com/open?id=1682kOjSX4eSaVn5Ui3uyBu5tORDQlY65

**Comment by kdjohnson** [comment]
<img width="1440" alt="screen shot 2018-01-27 at 5 43 35 pm" src="https://user-images.githubusercontent.com/11354738/35477074-c364165a-0389-11e8-8ca9-5429bc24df45.png">
<img width="1440" alt="screen shot 2018-01-27 at 5 44 11 pm" src="https://user-images.githubusercontent.com/11354738/35477075-c377300a-0389-11e8-8f18-6826f40925fb.png">
<img width="1439" alt="screen shot 2018-01-27 at 5 46 42 pm" src="https://user-images.githubusercontent.com/11354738/35477090-13aea99a-038a-11e8-9f1d-5d3af061966c.png">

**Comment by joshherkness** [comment]
Looks good

**Comment by joshherkness** [comment]
Can you make the delete button less noticeable? It's kinda popping out at me, drawing all my attention
