### ISSUE TITLE
Authentication endpoint

### ISSUE THREAD

**Issue by joshherkness** [joshherkness/AR-Top#8]
# Authentication endpoint

This endpoint will be used to authenticate a user with our API.

* **URL**
  * `/auth`

* **Method**
  * `POST`

* **URL Params**
  * _None_

* **Data Params**
  * `{ email=[alphanumeric], password=[alphanumeric] }`

* **Successful response**
  * **Code**: `200`
     **Content**: `{ user, auth_token }`

* **Error response**
  * **Code**: `422`
     **Content**: `{ error: "Incorrect email or password"}`

**Comment by jjrobertson14** [comment]
Is this issue just for the outline of the endpoint? Or does this issue also include api token generation and checking the email/password?

For what's outlined in the issue, I just have to do input validation

**Comment by joshherkness** [comment]
Do token generation also.

**Comment by joshherkness** [comment]
Look into something like [this](https://blog.miguelgrinberg.com/post/restful-authentication-with-flask).

**Comment by joshherkness** [comment]
Another example [here](https://github.com/miguelgrinberg/REST-auth/blob/master/api.py)
