### ISSUE TITLE
Map list component

### ISSUE THREAD

**Issue by joshherkness** [joshherkness/AR-Top#80]
Create the map list component as seen in the following mockup. https://drive.google.com/open?id=1682kOjSX4eSaVn5Ui3uyBu5tORDQlY65

**Comment by kdjohnson** [comment]
<img width="1440" alt="screen shot 2018-01-27 at 5 43 35 pm" src="https://user-images.githubusercontent.com/11354738/35477068-a85f2818-0389-11e8-92a2-7ec18830516e.png">
<img width="1440" alt="screen shot 2018-01-27 at 5 44 11 pm" src="https://user-images.githubusercontent.com/11354738/35477072-b6cad9ba-0389-11e8-8a2f-c4e1ad892785.png">

**Comment by kdjohnson** [comment]
@joshherkness  Do you want this to be displayed only on maps, the homepage, both?

**Comment by joshherkness** [comment]
For now, just display it on maps. We have yet to determine what goes on the home page.

**Comment by joshherkness** [comment]
Can you put more margin around the entire list and each card?  Also, more margin around the create a map button.
