### ISSUE TITLE
Sign out doesn't work

### ISSUE THREAD

**Issue by joshherkness** [joshherkness/AR-Top#92]
Sign out button doesn't work.

**Comment by kdjohnson** [comment]
I'm not able to reproduce this. I've tried in Firefox and Chrome. The only thing I can think of is that the  storage in your browser is somehow not receiving the mutations to the store.

**Comment by joshherkness** [comment]
Alright, let me try to see if It's something in my browser.

**Comment by kdjohnson** [comment]
Does the console throw any errors?

**Comment by joshherkness** [comment]
No
